[SpringBoard, BulletinBoard] Improvements
theos/headers pull request #42
Opened 2021-03-11 16:11 UTC by ryannair05

2021-03-13 20:52 UTC, lateef-class commented on BulletinBoard/BBBulletin.h
> +@property (nonatomic, retain) BBContent * content;
nitpick: space between `*` and variable name
```suggestion objc
@property (nonatomic, retain) BBContent *content;
```

2021-03-13 20:54 UTC, leptos-null commented on BulletinBoard/BBBulletin.h
> +@property (nonatomic, retain) BBContent * content;
nitpick: space between `*` and variable name
```suggestion objc
@property (nonatomic, retain) BBContent *content;
```

2021-03-13 20:59 UTC, leptos-null commented on SpringBoard/SBApplicationIcon.h
> +} SBIconImageInfo;
This struct exists in [SpringBoard/SBIconImageInfo.h](https://github.com/theos/headers/blob/819f49385304805f9a81e4210ae392c620505ea8/SpringBoard/SBIconImageInfo.h#L3-L7)

2021-03-13 21:09 UTC, leptos-null commented
Thank you for adding availability attributes! Looks great

2021-03-13 22:33 UTC, leptos-null approved these changes
Looks great- thanks!

2021-03-14 03:46 UTC, PoomSmart requested changes

2021-03-14 03:46 UTC, PoomSmart commented on SpringBoard/SBLockScreenManager.h
> +@property (nonatomic,readonly) CSCoverSheetViewController *coverSheetViewController API_AVAILABLE(ios(13.0));
```suggestion
@property (nonatomic, readonly) CSCoverSheetViewController *coverSheetViewController API_AVAILABLE(ios(13.0));
```

2021-03-15 06:23 UTC, PoomSmart approved these changes

2021-03-15 06:23 UTC, merged